trigger:
  branches:
    include:
      - master
  paths:
    include:
      - ci/*
      - environment.py
      - pylib/*
      - Connectors/src/AspDotNetCore/MySqlEFCore/*

variables:
  - group: 'Samples Configuration and Credentials'

jobs:
  -
    template: ../../../../ci/templates/cloud-foundry-job.yml
    parameters:
      feature: Connectors
      sample: MySqlEFCore
